/**
 * @file gui_demo_text.c
 * @brief text area demo
 * @author Duboisset Philippe
 * @version 0.1b
 * @date (yyyy-mm-dd) 2013-11-01
 *
 * Copyright (C) <2013>  Duboisset Philippe <duboisset.philippe@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "gui_demo_text.h"

#ifdef INCLUDE_GUI_DEMO

/*group #id*/
#define GRP_DEFAULT           0
#define GRP_DISABLED          2

/*widget' signals*/
#define SIG_DISABLE_OBJ       3
#define SIG_RADIO_TL          (G_ALIGN_H_LEFT   | G_ALIGN_V_TOP)
#define SIG_RADIO_TC          (G_ALIGN_H_CENTER | G_ALIGN_V_TOP)
#define SIG_RADIO_TR          (G_ALIGN_H_RIGHT  | G_ALIGN_V_TOP)
#define SIG_RADIO_CL          (G_ALIGN_H_LEFT   | G_ALIGN_V_CENTER)
#define SIG_RADIO_CC          (G_ALIGN_H_CENTER | G_ALIGN_V_CENTER)
#define SIG_RADIO_CR          (G_ALIGN_H_RIGHT  | G_ALIGN_V_CENTER)
#define SIG_RADIO_BL          (G_ALIGN_H_LEFT   | G_ALIGN_V_BOTTOM)
#define SIG_RADIO_BC          (G_ALIGN_H_CENTER | G_ALIGN_V_BOTTOM)
#define SIG_RADIO_BR          (G_ALIGN_H_RIGHT  | G_ALIGN_V_BOTTOM)

/**
 * local function
 */
void Gui_DemoTextHandler(signal_t sig);

/**
 * local variables
 */
static uint8_t disableObj;
static gui_align_t align = SIG_RADIO_TL;


/**
 * @function Gui_DemoText
 * @brief text area demo
 * @param signal_t sig: unused
 * @return none
 */
void Gui_DemoText(signal_t sig) {

  rect_st rec;
  disableObj = 0;

  Gui_DemoNewPage("Text area");

  rec = GUI_Rect(10, 20, 299, 137);
  GUI_SetAlign(align);
  GUI_SetGroup(GRP_DISABLED);
  GUI_W_TextAdd(&rec,
      "This program is free software: you can redistribute it and/or modify "
      "it under the terms of the GNU General Public License as published by "
      "the Free Software Foundation, either version 3 of the License, or "
      "(at your option) any later version.");
  GUI_SetGroup(GRP_DEFAULT);
  GUI_SetAlign(0); /*reset the alignment (recommended)*/

  /*draw the dimension of the text area*/
  rec.x--;
  rec.y--;
  rec.w += 2;
  rec.h += 2;
  P2D_SetLineType(LINE_SOLID);
  P2D_SetColor(COLOR_PURPLE);
  P2D_Rect(&rec);


  /**
   * alignment controls
   */
  rec = GUI_Rect(253, 160, 17, 17);
  GUI_W_RadioAdd(&rec, NULL, &align, SIG_RADIO_TL);
  GUI_SetSignal(E_PUSHED_TO_RELEASED, SIG_RADIO_TL);
  rec = GUI_Rect(273, 160, 17, 17);
  GUI_W_RadioAdd(&rec, NULL, &align, SIG_RADIO_TC);
  GUI_SetSignal(E_PUSHED_TO_RELEASED, SIG_RADIO_TC);
  rec = GUI_Rect(293, 160, 17, 17);
  GUI_W_RadioAdd(&rec, NULL, &align, SIG_RADIO_TR);
  GUI_SetSignal(E_PUSHED_TO_RELEASED, SIG_RADIO_TR);

  rec = GUI_Rect(253, 178, 17, 17);
  GUI_W_RadioAdd(&rec, NULL, &align, SIG_RADIO_CL);
  GUI_SetSignal(E_PUSHED_TO_RELEASED, SIG_RADIO_CL);
  rec = GUI_Rect(273, 178, 17, 17);
  GUI_W_RadioAdd(&rec, NULL, &align, SIG_RADIO_CC);
  GUI_SetSignal(E_PUSHED_TO_RELEASED, SIG_RADIO_CC);
  rec = GUI_Rect(293, 178, 17, 17);
  GUI_W_RadioAdd(&rec, NULL, &align, SIG_RADIO_CR);
  GUI_SetSignal(E_PUSHED_TO_RELEASED, SIG_RADIO_CR);

  rec = GUI_Rect(253, 196, 17, 17);
  GUI_W_RadioAdd(&rec, NULL, &align, SIG_RADIO_BL);
  GUI_SetSignal(E_PUSHED_TO_RELEASED, SIG_RADIO_BL);
  rec = GUI_Rect(273, 196, 17, 17);
  GUI_W_RadioAdd(&rec, NULL, &align, SIG_RADIO_BC);
  GUI_SetSignal(E_PUSHED_TO_RELEASED, SIG_RADIO_BC);
  rec = GUI_Rect(293, 196, 17, 17);
  GUI_W_RadioAdd(&rec, NULL, &align, SIG_RADIO_BR);
  GUI_SetSignal(E_PUSHED_TO_RELEASED, SIG_RADIO_BR);

  /**
   * disable control
   */
  rec = GUI_Rect(10, 160, 115, 19);
  GUI_W_CheckBoxAdd(&rec, "Disable objects", &disableObj);
  GUI_SetSignal(E_PUSHED_TO_RELEASED, SIG_DISABLE_OBJ);

  /* => page creation is now completed. Jump to the page's handler*/
  GUI_SetUserTask(Gui_DemoTextHandler);
}



/**
 * @function Gui_DemoTextHandler
 * @brief text area demo handler
 * @param signal_t sig: signal coming from widgets
 * @return none
 */
void Gui_DemoTextHandler(signal_t sig) {

  switch(sig) {

    /*widget control*/
    case SIG_DISABLE_OBJ:
      disableObj = !disableObj;
      GUI_GroupDisable(GRP_DISABLED, disableObj);
      break;

    /*'menu' button*/
    case SIG_DEMO_MENU:
      GUI_SetUserTask(Gui_Demo);
      break;

    /*no signal*/
    case 0:
      break;

    /*at this point, the signal has been generated by a radio*/
    default:
      align = sig;
      GUI_SetUserTask(Gui_DemoText);
      break;
  }
}

#endif
